export default class AchievementMapInfo {
  off_3: ResourceStr = $r('app.media.ic_badge_3_off');
  on_3: ResourceStr = $r('app.media.ic_badge_3_on');
  off_7: ResourceStr = $r('app.media.ic_badge_7_off');
  on_7: ResourceStr = $r('app.media.ic_badge_7_on');
  off_30: ResourceStr = $r('app.media.ic_badge_30_off');
  on_30: ResourceStr = $r('app.media.ic_badge_30_on');
  off_50: ResourceStr = $r('app.media.ic_badge_50_off');
  on_50: ResourceStr = $r('app.media.ic_badge_50_on');
  off_73: ResourceStr = $r('app.media.ic_badge_73_off');
  on_73: ResourceStr = $r('app.media.ic_badge_73_on');
  off_99: ResourceStr = $r('app.media.ic_badge_99_off');
  on_99: ResourceStr = $r('app.media.ic_badge_99_on');
}